### ISSUE TITLE
respawnall bugged

### ISSUE THREAD

**Issue by ThePhoenix96** [Guarmanda/LootChest#1]
Server version: [18:32:53] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-f56e2e7-1a64d4a (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)[m
[18:32:53] [Server thread/INFO]: Checking version, please wait...[m
[18:32:53] [Thread-60/INFO]: You are running the latest version[m

cant use respawn or respawnall command

`[18:22:06] [Server thread/INFO]: AvTo_ issued server command: /lc respawnall
[18:22:06] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'lc' in plugin LootChest v1.6.7
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-1a64d4a]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-1a64d4a]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-1a64d4a]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1636) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-1a64d4a]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1476) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-1a64d4a]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-1a64d4a]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-1a64d4a]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-1a64d4a]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_191]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-f56e2e7-1a64d4a]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot-1.13.2.jar:git-Spigot-f56e2e7-1a64d4a]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-f56e2e7-1a64d4a]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-f56e2e7-1a64d4a]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-f56e2e7-1a64d4a]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_13_R2.block.CraftBlock cannot be cast to org.bukkit.block.Chest
	at fr.black_eyes.lootchest.Utils.restoreChest(Utils.java:129) ~[?:?]
	at fr.black_eyes.lootchest.commands.Lootchest.onCommand(Lootchest.java:110) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-1a64d4a]
	... 15 more`

**Comment by Guarmanda** [comment]
Thanks for the report, I'll test that as soon as I'm home

**Comment by Guarmanda** [comment]
Fixed, last update was just uploaded to spigot.

**Comment by ThePhoenix96** [comment]
ty
