### ISSUE TITLE
NoSuchMethodException in 1.12.2 on "/lc create"

### ISSUE THREAD

**Issue by Toshimichi0915** [Guarmanda/LootChest#10]
"/lc create <name>" causes an exception.
Tested versions: 1.12.2(Spigot, Paper)
```
org.bukkit.command.CommandException: Unhandled exception executing command 'lc' in plugin LootChest v2.1.5
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1401) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1236) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_231]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_231]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
Caused by: org.inventivetalent.particle.ParticleException: Failed to send particle SMOKE_NORMAL to [CraftPlayer{name=Toshimichi0915}]
        at org.inventivetalent.particle.ParticleEffect$Particle.send(ParticleEffect.java:445) ~[?:?]
        at org.inventivetalent.particle.ParticleEffect.send(ParticleEffect.java:294) ~[?:?]
        at org.inventivetalent.particle.ParticleEffect.send(ParticleEffect.java:256) ~[?:?]
        at org.inventivetalent.particle.ParticleEffect.send(ParticleEffect.java:277) ~[?:?]
        at fr.black_eyes.lootchest.falleffect.FallingPackageEntity.tick(FallingPackageEntity.java:127) ~[?:?]
        at fr.black_eyes.lootchest.falleffect.FallingPackageEntity.summon(FallingPackageEntity.java:97) ~[?:?]
        at fr.black_eyes.lootchest.falleffect.FallingPackageEntity.<init>(FallingPackageEntity.java:57) ~[?:?]
        at fr.black_eyes.lootchest.Utils.restoreChest(Utils.java:335) ~[?:?]
        at fr.black_eyes.lootchest.commands.LootchestCommand.onCommand(LootchestCommand.java:135) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        ... 15 more
Caused by: java.lang.NoSuchMethodException: Could not resolve constructor for [ResolverQuery{name='null', types=[class net.minecraft.server.v1_12_R1.EnumParticle, boolean, float, float, float, float, float, float, float, int]}] in class class net.minecraft.server.v1_12_R1.PacketPlayOutWorldParticles
        at org.inventivetalent.reflection.resolver.ConstructorResolver.notFoundException(ConstructorResolver.java:105) ~[?:?]
        at org.inventivetalent.reflection.resolver.ConstructorResolver.notFoundException(ConstructorResolver.java:1) ~[?:?]
        at org.inventivetalent.reflection.resolver.ResolverAbstract.resolve(ResolverAbstract.java:60) ~[?:?]
        at org.inventivetalent.reflection.resolver.ConstructorResolver.resolve(ConstructorResolver.java:60) ~[?:?]
        at org.inventivetalent.particle.ParticleEffect$Particle.send_1_13(ParticleEffect.java:450) ~[?:?]
        at org.inventivetalent.particle.ParticleEffect$Particle.send(ParticleEffect.java:437) ~[?:?]
        at org.inventivetalent.particle.ParticleEffect.send(ParticleEffect.java:294) ~[?:?]
        at org.inventivetalent.particle.ParticleEffect.send(ParticleEffect.java:256) ~[?:?]
        at org.inventivetalent.particle.ParticleEffect.send(ParticleEffect.java:277) ~[?:?]
        at fr.black_eyes.lootchest.falleffect.FallingPackageEntity.tick(FallingPackageEntity.java:127) ~[?:?]
        at fr.black_eyes.lootchest.falleffect.FallingPackageEntity.summon(FallingPackageEntity.java:97) ~[?:?]
        at fr.black_eyes.lootchest.falleffect.FallingPackageEntity.<init>(FallingPackageEntity.java:57) ~[?:?]
        at fr.black_eyes.lootchest.Utils.restoreChest(Utils.java:335) ~[?:?]
        at fr.black_eyes.lootchest.commands.LootchestCommand.onCommand(LootchestCommand.java:135) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        ... 15 more
        ```

**Comment by Guarmanda** [comment]
:O Will test any version today, thanks for repporting

**Comment by Guarmanda** [comment]
fixed, will update on spigot now. Particles weren't working in 1.12.2 only^^
