### ISSUE TITLE
Maximum number of chests ?

### ISSUE THREAD

**Issue by Sawich94** [Guarmanda/LootChest#11]
How to increase the maximum number of chests?
We have created about 40 chests, and now when creating a new chest, we cannot copy the settings from the old one, what could be the problem?

It seems to us that this is due to the fact that the "main chest" with other chests is full.

Server version SpigotForge 1.12.2

https://i.imgur.com/JzIsHJ3.png
https://i.imgur.com/2R9hHbn.png

**Comment by Guarmanda** [comment]
You mean that this inventory lacks chests because you created too much chests ?! I thought I did a menu with several pages to prevent this problem, but maybe I didn't do it the right way :/

**Comment by Sawich94** [comment]
Thank you for your prompt response, I recorded a video, so it will probably be clear what I mean. And unfortunately there is no second page. We are creating a server on 1.12.2
Is this possible to solve?

https://youtu.be/8utuJkhewn0

**Comment by Sawich94** [comment]
I hope you can solve this problem :>

**Comment by Guarmanda** [comment]
OK so the copy menu totally crashes when there's too much of it... You sure have a console error with this, but I can reproduce it myself^^ I'll fox it when I have some time off

**Comment by Sawich94** [comment]
According to your instructions, I found this error in the console. I hope you have some time today :>

```
> (10:03:06|INFO): Sawich issued server command: /lc create 001
> (10:03:22|ERROR): Could not pass event InventoryClickEvent to LootChest v1.7
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[JavaPluginLoader$1.class:1.12.2-2838]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.12.2-2838]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [SimplePluginManager.class:1.12.2-2838]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [SimplePluginManager.class:1.12.2-2838]
at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2074) [pa.class:?]
at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) [lf.class:?]
at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) [lf.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) [hv$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_275]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_275]
at net.minecraft.util.Util.func_181617_a(Util.java:50) [h.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:797) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:478) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:739) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:627) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 54
at java.util.Arrays$ArrayList.set(Arrays.java:3846) ~[?:1.8.0_275]
at net.minecraft.util.NonNullList.set(NonNullList.java:54) ~[fi.class:?]
at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftInventoryCustom$MinecraftInventory.func_70299_a(CraftInventoryCustom.java:124) ~[CraftInventoryCustom$MinecraftInventory.class:1.12.2-2838]
at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftInventory.setItem(CraftInventory.java:101) ~[CraftInventory.class:1.12.2-2838]
at fr.black_eyes.lootchest.Utils.invcopy(Utils.java:387) ~[?:?]
at fr.black_eyes.lootchest.listeners.InventoryListeners.onClick(InventoryListeners.java:162) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_275]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_275]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[JavaPluginLoader$1.class:1.12.2-2838]
```

**Comment by Guarmanda** [comment]
You're using a very old version of the plugin, update it and it should work

**Comment by Sawich94** [comment]
> You're using a very old version of the plugin, update it and it should work

huh, thanks : D
