### ISSUE TITLE
An internal error occured while attempting to perform LootChest commands 

### ISSUE THREAD

**Issue by Berrysssss** [Guarmanda/LootChest#14]
This is what it showed whenever i used a LootChest command

lc randomspawn SupplyCrate 10000
[07:26:15 INFO]: You set a spawn radius for chest SupplyCrate. From now, it will spawn at this radius around the place where the chest was created, or around a random player if you set "use_players_locations_for_randomspawn" to true.
[07:26:15 WARN]: Unexpected exception while parsing console command "lc randomspawn SupplyCrate 10000"
org.bukkit.command.CommandException: Unhandled exception executing command 'lc' in plugin LootChest v2.1.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.4.jar:git-Paper-416]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.4.jar:git-Paper-416]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:807) ~[patched_1.16.4.jar:git-Paper-416]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:769) ~[patched_1.16.4.jar:git-Paper-416]
        at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:411) ~[patched_1.16.4.jar:git-Paper-416]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:378) ~[patched_1.16.4.jar:git-Paper-416]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1208) ~[patched_1.16.4.jar:git-Paper-416]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:996) ~[patched_1.16.4.jar:git-Paper-416]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-416]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException

**Comment by Guarmanda** [comment]
This is the whole error, nothing more? That's weird, there's not any line speaking about a file of my plugin, so that I can't know what is causing this bug :/

**Comment by Berrysssss** [comment]
> This is the whole error, nothing more? That's weird, there's not any line speaking about a file of my plugin, so that I can't know what is causing this bug :/

oh, alright then i guess its my server, ill try to figure it out with my developer. thanks anyways

**Comment by Guarmanda** [comment]
maybe it's not your server, executing the command is clearly the cause of the error, I'm just saying I don't see anything that says where is the error in my plugin, so if it's my plugin, I can't fix it

**Comment by Berrysssss** [comment]
alright, is there a way that i can fix this? or should i just ask in another platform community or whatever, im still confused on what to do since im not that good on coding and such.. and sorry if my grammar is a bit childish my main language isnt english lol.

**Comment by Guarmanda** [comment]
Well if it appens only with my plugin's commands, it comes from my plugin. If you don't have other lines in your error I won't be able to fix it, but at least you'll know where it comes from... If it's my plugin, you can try deleting the "lootchest" folder for generate a new one^^

**Comment by Berrysssss** [comment]
alrighty, again, thanks!
