### ISSUE TITLE
Unknown Issues

### ISSUE THREAD

**Issue by WilSwo** [Guarmanda/LootChest#19]
Hi there! I love your plugin, and we have been running it for a while. We are making the switch to 1.17.1 - and this is what I am noticing now upon starting the plugin. It does this over/over again. I'm not sure what is going on. If you have any advice/thoughts I'd apreciate them! Thank you!

[19:28:43 WARN]: [LootChest] Task #1962 for LootChest v2.2.7 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Entity.setCustomName(String)" because "as" is null
        at fr.black_eyes.lootchest.Hologram$1.run(Hologram.java:124) ~[LootChest.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-187]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-187]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1490) ~[patched_1.17.1.jar:git-Paper-187]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-187]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Paper-187]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1188) ~[patched_1.17.1.jar:git-Paper-187]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-187]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[19:28:43 WARN]: [LootChest] Task #1966 for LootChest v2.2.7 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Entity.setCustomName(String)" because "as" is null
        at fr.black_eyes.lootchest.Hologram$1.run(Hologram.java:124) ~[LootChest.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-187]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-187]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1490) ~[patched_1.17.1.jar:git-Paper-187]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-187]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Paper-187]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1188) ~[patched_1.17.1.jar:git-Paper-187]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-187]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[19:28:43 INFO]: [LootChest] Armorstand found (uuid)

**Comment by Guarmanda** [comment]
Yes, it'll be fixed in next version (I already fixed it in the code on my computer)

**Comment by WilSwo** [comment]
Awesome!

Thank you much!
