### ISSUE TITLE
Error occurred while enabling LootChest v2.3.2 (Is it up to date?)

### ISSUE THREAD

**Issue by Beartherter13** [Guarmanda/LootChest#32]
Hi creator ! I have some problem with plugin ... vers 1.15.2 paper 

Console error: 

[10:54:59 ERROR]: Error occurred while enabling LootChest v2.3.2 (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.SOUL_LANTERN
        at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_301]
        at org.bukkit.Material.valueOf(Material.java:85) ~[patched_1.15.2.jar:git-Paper-391]
        at fr.black_eyes.lootchest.Mat.init_materials(Mat.java:102) ~[?:?]
        at fr.black_eyes.lootchest.Main.onEnable(Main.java:110) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-391]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-391]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-391]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-391]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:909) ~[patched_1.15.2.jar:git-Paper-391]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_301]
[10:54:59 INFO]: [LootChest] Disabling LootChest v2.3.2
[10:54:59 ERROR]: Error occurred while disabling LootChest v2.3.2 (Is it up to date?)
java.lang.NullPointerException: null
        at fr.black_eyes.lootchest.Files.saveData(Files.java:32) ~[?:?]
        at fr.black_eyes.lootchest.Utils.updateData(Utils.java:555) ~[?:?]
        at fr.black_eyes.lootchest.Main.onDisable(Main.java:61) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.15.2.jar:git-Paper-391]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.15.2.jar:git-Paper-391]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.15.2.jar:git-Paper-391]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.15.2.jar:git-Paper-391]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-391]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-391]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:909) ~[patched_1.15.2.jar:git-Paper-391]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_301]

**Comment by Guarmanda** [comment]
Corrected for next version, thx for report, in fact soul lantern appeared in 1.16 and not 1.15 so the plugin couln't work correctly on 1.15 :/

**Comment by Beartherter13** [comment]
Cheked

**Comment by Beartherter13** [comment]
[20:23:12 ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'lc' in plugin LootChest v2.3.3 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.15.2.jar:git-Paper-391]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-391]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1869) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1677) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1106) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1099) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1233) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:971) ~[patched_1.15.2.jar:git-Paper-391]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_301]

**Comment by Beartherter13** [comment]
[Log.txt](https://github.com/Guarmanda/LootChest/files/8985274/Log.txt)

**Comment by Beartherter13** [comment]
null
org.bukkit.command.CommandException: Cannot execute command 'lc' in plugin LootChest v2.3.3 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.15.2.jar:git-Paper-391]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-391]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1869) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1677) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1106) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1099) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1233) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:971) ~[patched_1.15.2.jar:git-Paper-391]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_301]

**Comment by Guarmanda** [comment]
there was an error before this one can you send me the first error?

**Comment by Beartherter13** [comment]
Only this

**Comment by Beartherter13** [comment]
sec, no !
[Log.txt](https://github.com/Guarmanda/LootChest/files/8987339/Log.txt)

**Comment by Beartherter13** [comment]
I see this message

**Comment by Beartherter13** [comment]
SOUL_LANTERN again , this plugin i cheked after fix

**Comment by Guarmanda** [comment]
very, very weird O_o I'll have to test this myself on my local server

**Comment by Beartherter13** [comment]
Hmm , idk , how fix it ?

**Comment by Guarmanda** [comment]
I idn't correctly update the plugin, the version online isn't the correct version :/

**Comment by Guarmanda** [comment]
solved, it should be downloadable soon or now

**Comment by Beartherter13** [comment]
FIXED

**Comment by Beartherter13** [comment]
I had an idea to make a legendary chest on the server, but the functionality of this plugin is not enough. The point is that when you try to open the chest there are spawned mobs and to take loot you need to kill several such waves with mobs. 

Can you try to do this function?

Thanks!

**Comment by Guarmanda** [comment]
There is an event that is thrown at chest spawn, can't really to more than that (LootChestSpawnEvent)
