### ISSUE TITLE
Loot Chest error

### ISSUE THREAD

**Issue by DezApical** [Guarmanda/LootChest#41]
[17:53:15] [Server thread/WARN]: [LootChest] Task #397 for LootChest v2.3.3 generated an exception
--
836 | java.lang.NullPointerException: Cannot invoke "org.bukkit.Material.equals(Object)" because "this.type" is null
837 | at fr.black_eyes.lootchest.Lootchest.isGoodType(Lootchest.java:331) ~[LootChest.jar:?]
838 | at fr.black_eyes.lootchest.Utils.restoreChest(Utils.java:321) ~[LootChest.jar:?]
839 | at fr.black_eyes.lootchest.Main$2.lambda$1(Main.java:253) ~[LootChest.jar:?]
840 | at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-388]
841 | at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-388]
842 | at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1532) ~[paper-1.18.2.jar:git-Paper-388]
843 | at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-388]
844 | at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-388]
845 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-388]
846 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
847 | at java.lang.Thread.run(Thread.java:833)

[17:56:37] [Server thread/ERROR]: Error occurred while disabling LootChest v2.3.3 (Is it up to date?)
--
967 | java.lang.NullPointerException: Cannot invoke "org.bukkit.Material.name()" because "this.type" is null
968 | at fr.black_eyes.lootchest.Lootchest.saveInConfig(Lootchest.java:267) ~[LootChest.jar:?]
969 | at fr.black_eyes.lootchest.Utils.updateData(Utils.java:553) ~[LootChest.jar:?]
970 | at fr.black_eyes.lootchest.Main.onDisable(Main.java:61) ~[LootChest.jar:?]
971 | at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
972 | at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
973 | at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:578) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
974 | at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:555) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
975 | at org.bukkit.craftbukkit.v1_18_R2.CraftServer.disablePlugins(CraftServer.java:494) ~[paper-1.18.2.jar:git-Paper-388]
976 | at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:972) ~[paper-1.18.2.jar:git-Paper-388]
977 | at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:803) ~[paper-1.18.2.jar:git-Paper-388]
978 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1271) ~[paper-1.18.2.jar:git-Paper-388]
979 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
980 | at java.lang.Thread.run(Thread.java:833) ~[?:?]

</body>
</html>[17:56:37] [Server thread/ERROR]: Error occurred while disabling LootChest v2.3.3 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.bukkit.Material.name()" because "this.type" is null
	at fr.black_eyes.lootchest.Lootchest.saveInConfig(Lootchest.java:267) ~[LootChest.jar:?]
	at fr.black_eyes.lootchest.Utils.updateData(Utils.java:553) ~[LootChest.jar:?]
	at fr.black_eyes.lootchest.Main.onDisable(Main.java:61) ~[LootChest.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:578) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:555) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.disablePlugins(CraftServer.java:494) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:[972](https://aternos.org/log/#L972)) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:803) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1271) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Guarmanda** [comment]
weird, I hope it had appenned only once?
