### ISSUE TITLE
Drop-in replacement of .jar won't work with latest

### ISSUE THREAD

**Issue by mrfloris** [Guarmanda/LootChest#56]
```
[11:36:19 INFO]: [LootChest] Added config option 'SaveDataFileDuringReload' in config.yml
[11:36:19 INFO]: [LootChest] Starting particles...
[11:36:19 ERROR]: Error occurred while enabling LootChest v2.3.6 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at fr.black_eyes.lootchest.Main.initParticles(Main.java:457) ~[LootChest-2.3.6.jar:?]
        at fr.black_eyes.lootchest.Main.onEnable(Main.java:191) ~[LootChest-2.3.6.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[paper-1.20.2.jar:git-Paper-318]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:646) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:557) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-318]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Invalid or unsupported particle type: DUST_PLUME
        at fr.black_eyes.lootchest.particles.ParticleTypes.of(ParticleTypes.java:54) ~[LootChest-2.3.6.jar:?]
        at fr.black_eyes.lootchest.particles.ParticleType.of(ParticleType.java:16) ~[LootChest-2.3.6.jar:?]
        at fr.black_eyes.lootchest.particles.Particle.<init>(Particle.java:171) ~[LootChest-2.3.6.jar:?]
        at fr.black_eyes.lootchest.particles.Particle.<clinit>(Particle.java:54) ~[LootChest-2.3.6.jar:?]
        ... 14 more
[11:36:19 INFO]: [LootChest] Disabling LootChest v2.3.6
[11:36:19 INFO]: [LootChest] Backed up data file in case of crash
```
The changelog was reviewed before upgrading, https://www.spigotmc.org/resources/lootchest.61564/update?update=531471 but doesn't imply that I have to make some manual changes, or that this is now for a specific Minecraft version (just 1.20, so I assume 1.20.2 fall under this?)

DUST_PLUME doesn't appear in any of the configuration YAML files, so it's not something I can fix myself.

```
 This server is running Paper version git-Paper-318 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9271ee7)
```
If you need any further information please let me know.

**Comment by Guarmanda** [comment]
You're running 1.20.2, and there was stupid particles changes between 1.20 and 1.20.4: DUST_PLUME doesn't exist in 1.20.2 but my plugin tries to load it because it only checks if you're in 1.20... I should may check if you're in 1.20.4 precisely

**Comment by Guarmanda** [comment]
Fixed in the code, will be fixed in next version
