### ISSUE TITLE
Paper 1.21 + Lootchest fails to load

### ISSUE THREAD

**Issue by mrfloris** [Guarmanda/LootChest#64]
I will send you a PM on Spigot with the latest.log - rather not include it here.
```
[18:48:12] [Server thread/INFO]: [LootChest] Enabling LootChest v2.4.0
[18:48:12] [Server thread/INFO]: [LootChest] Server version: 1.21
[18:48:12] [Server thread/INFO]: [LootChest] Loading config files...
[18:48:12] [Server thread/INFO]: [LootChest] Starting particles...
[18:48:12] [Server thread/ERROR]: Error occurred while enabling LootChest v2.4.0 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at LootChest.jar/fr.black_eyes.lootchest.particles.ParticleTypes.<clinit>(ParticleTypes.java:18) ~[LootChest.jar:?]
	at LootChest.jar/fr.black_eyes.lootchest.particles.ParticleType.of(ParticleType.java:16) ~[LootChest.jar:?]
	at LootChest.jar/fr.black_eyes.lootchest.particles.Particle.<init>(Particle.java:171) ~[LootChest.jar:?]
	at LootChest.jar/fr.black_eyes.lootchest.particles.Particle.<clinit>(Particle.java:30) ~[LootChest.jar:?]
	at LootChest.jar/fr.black_eyes.lootchest.Main.initParticles(Main.java:502) ~[LootChest.jar:?]
	at LootChest.jar/fr.black_eyes.lootchest.Main.onEnable(Main.java:204) ~[LootChest.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-26-77c763b]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-26-77c763b]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:629) ~[paper-1.21.jar:1.21-26-77c763b]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:578) ~[paper-1.21.jar:1.21-26-77c763b]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:690) ~[paper-1.21.jar:1.21-26-77c763b]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:452) ~[paper-1.21.jar:1.21-26-77c763b]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:327) ~[paper-1.21.jar:1.21-26-77c763b]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157) ~[paper-1.21.jar:1.21-26-77c763b]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-26-77c763b]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.StringIndexOutOfBoundsException: Range [23, 22) out of bounds for length 22
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55) ~[?:?]
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52) ~[?:?]
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213) ~[?:?]
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210) ~[?:?]
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98) ~[?:?]
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112) ~[?:?]
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349) ~[?:?]
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4914) ~[?:?]
	at java.base/java.lang.String.substring(String.java:2876) ~[?:?]
	at java.base/java.lang.String.substring(String.java:2849) ~[?:?]
	at LootChest.jar/fr.black_eyes.lootchest.particles.FastReflection.<clinit>(FastReflection.java:18) ~[LootChest.jar:?]
	... 18 more
[18:48:12] [Server thread/INFO]: [LootChest] Disabling LootChest v2.4.0
[18:48:12] [Server thread/INFO]: [LootChest] Backed up data file in case of crash
```

**Comment by Submons** [comment]
same error with particles on V1.20.6...

**Comment by Guarmanda** [comment]
Update posted
