### ISSUE TITLE
NPE error.

### ISSUE THREAD

**Issue by yiyoperez** [Guarmanda/LootChest#68]
I got this error a while ago when I was testing the plugin.
I saw that you updated and I don't really know if its fixed so I report it anyway. (You can close this issue if fixed, mb)

```
[21:50:19 ERROR]: Could not pass event InventoryCloseEvent to LootChest v2.4.1
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "menuName" is null
        at fr.black_eyes.lootchest.listeners.InventoryListeners.oncloseInventory(InventoryListeners.java:61) ~[LootChest.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor272.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:git-Pufferfish-39]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[pufferfish-1.20.4.jar:git-Pufferfish-39]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[pufferfish-1.20.4.jar:git-Pufferfish-39]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1678) ~[pufferfish-1.20.4.jar:git-Pufferfish-39]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:2869) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:2862) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClosePacket.handle(ServerboundContainerClosePacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClosePacket.a(ServerboundContainerClosePacket.java:10) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.20.4.jar:git-Pufferfish-39]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1466) ~[pufferfish-1.20.4.jar:git-Pufferfish-39]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[pufferfish-1.20.4.jar:git-Pufferfish-39]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1443) ~[pufferfish-1.20.4.jar:git-Pufferfish-39]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1366) ~[pufferfish-1.20.4.jar:git-Pufferfish-39]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1344) ~[pufferfish-1.20.4.jar:git-Pufferfish-39]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1228) ~[pufferfish-1.20.4.jar:git-Pufferfish-39]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[pufferfish-1.20.4.jar:git-Pufferfish-39]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

```

**Comment by Guarmanda** [comment]
What is "a while ago" 😅

**Comment by yiyoperez** [comment]
> What is "a while ago" 😅

mb, it was on 1st of july

**Comment by Guarmanda** [comment]
Wow, so no, not fixed 😬

**Comment by Guarmanda** [comment]
Inventory are totally recoded in next version, I think it will be solved
