### ISSUE TITLE
1.21.1 Support

### ISSUE THREAD

**Issue by IasonKalaitzakis** [Guarmanda/LootChest#70]
Can the plugin support 1.21.1? It was a super small update anyway so I doubt any work needs to be done on it. Thanks :)

**Comment by IasonKalaitzakis** [comment]
I tried, got the following error:

`[11:49:40] [Server thread/INFO]: [LootChest] Enabling LootChest v2.4.4
[11:49:40] [Server thread/WARN]: [LootChest] Unsupported server version: 1.21.1-12-1798e94 (MC: 1.21.1)
[11:49:40] [Server thread/WARN]: [LootChest] Plugin will be disabled.
[11:49:40] [Server thread/INFO]: [LootChest] Disabling LootChest v2.4.4
[11:49:40] [Server thread/ERROR]: Error occurred while disabling LootChest v2.4.4
java.lang.NullPointerException: Cannot invoke "eu.decentholo.holograms.api.holograms.HologramManager.destroy()" because "this.hologramManager" is null
	at LootChest.jar/eu.decentholo.holograms.api.DecentHolograms.disable(DecentHolograms.java:75) ~[LootChest.jar:?]
	at LootChest.jar/eu.decentholo.holograms.api.DecentHologramsAPI.onDisable(DecentHologramsAPI.java:65) ~[LootChest.jar:?]
	at LootChest.jar/eu.decentholo.holograms.DecentHologramsPlugin.onDisable(DecentHologramsPlugin.java:24) ~[LootChest.jar:?]
	at LootChest.jar/fr.black_eyes.lootchest.Main.onDisable(Main.java:84) ~[LootChest.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.21.1.jar:1.21.1-12-1798e94]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[paper-1.21.1.jar:1.21.1-12-1798e94]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at LootChest.jar/eu.decentholo.holograms.api.DecentHolograms.load(DecentHolograms.java:54) ~[LootChest.jar:?]
	at LootChest.jar/eu.decentholo.holograms.api.DecentHologramsAPI.onLoad(DecentHologramsAPI.java:36) ~[LootChest.jar:?]
	at LootChest.jar/eu.decentholo.holograms.DecentHologramsPlugin.onLoad(DecentHologramsPlugin.java:13) ~[LootChest.jar:?]
	at LootChest.jar/fr.black_eyes.lootchest.Main.onEnable(Main.java:150) ~[LootChest.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-12-1798e94]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-12-1798e94]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.1.jar:1.21.1-12-1798e94]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.1.jar:1.21.1-12-1798e94]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754) ~[paper-1.21.1.jar:1.21.1-12-1798e94]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516) ~[paper-1.21.1.jar:1.21.1-12-1798e94]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-12-1798e94]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.1.jar:1.21.1-12-1798e94]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-12-1798e94]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[11:49:40] [Server thread/ERROR]: Error occurred while enabling LootChest v2.4.4 (Is it up to date?)
java.lang.IllegalStateException: zip file closed
	at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:846) ~[?:?]
	at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:338) ~[?:?]
	at java.base/java.util.jar.JarFile.getEntry(JarFile.java:516) ~[?:?]
	at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:471) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:209) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at LootChest.jar/eu.decentholo.holograms.api.DecentHolograms.enable(DecentHolograms.java:59) ~[LootChest.jar:?]
	at LootChest.jar/eu.decentholo.holograms.api.DecentHologramsAPI.onEnable(DecentHologramsAPI.java:51) ~[LootChest.jar:?]
	at LootChest.jar/eu.decentholo.holograms.DecentHologramsPlugin.onEnable(DecentHologramsPlugin.java:18) ~[LootChest.jar:?]
	at LootChest.jar/fr.black_eyes.lootchest.Main.onEnable(Main.java:151) ~[LootChest.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-12-1798e94]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-12-1798e94]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.1.jar:1.21.1-12-1798e94]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.1.jar:1.21.1-12-1798e94]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754) ~[paper-1.21.1.jar:1.21.1-12-1798e94]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516) ~[paper-1.21.1.jar:1.21.1-12-1798e94]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-12-1798e94]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.1.jar:1.21.1-12-1798e94]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-12-1798e94]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]`

**Comment by Guarmanda** [comment]
Hem, I was right, holograms does not work XD

**Comment by Guarmanda** [comment]
fixed in last version (2.4.5) 1b79e6b
