### ISSUE TITLE
Copy menu error

### ISSUE THREAD

**Issue by Guarmanda** [Guarmanda/LootChest#73]
[04:10:58] [Server thread/ERROR]: Could not pass event InventoryClickEvent to LootChest v2.4.5
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[forge:?]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge:?]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:593) ~[forge:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:578) ~[forge:?]
at net.minecraft.network.play.ServerPlayNetHandler.func_147351_a(ServerPlayNetHandler.java:2277) ~[?:?]
at net.minecraft.network.play.client.CClickWindowPacket.func_148833_a(CClickWindowPacket.java:34) ~[?:?]
at net.minecraft.network.play.client.CClickWindowPacket.func_148833_a(CClickWindowPacket.java:12) ~[?:?]
at net.minecraft.network.PacketThreadUtil.func_225383_a(PacketThreadUtil.java:22) ~[?:?]
at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:885) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:169) ~[?:?]
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:868) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:862) ~[?:?]
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:848) ~[?:?]
at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:779) ~[?:?]
at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:265) ~[?:?]
at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "fr.black_eyes.lootchest.Lootchest.getHolo()" because "chest1" is null
at fr.black_eyes.lootchest.Utils.copychest(Utils.java:89) ~[?:?]
at fr.black_eyes.lootchest.listeners.InventoryListeners.onClick(InventoryListeners.java:173) ~[?:?]
at jdk.internal.reflect.GeneratedMethodAccessor48.invoke(Unknown Source) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[forge:?]
... 20 more

-----------------------------------------------------------------
[04:38:06] [Server thread/WARN]: [LootChest] Task #633 for LootChest v2.4.5 generated an exception
java.lang.IllegalArgumentException: Hologram name can only contain alphanumeric characters, underscores and dashes! (小型弹药箱)
at eu.decentholo.holograms.api.DHAPI.createHologram(DHAPI.java:85) ~[?:?]
at eu.decentholo.holograms.api.DHAPI.createHologram(DHAPI.java:53) ~[?:?]
at eu.decentholo.holograms.api.DHAPI.createHologram(DHAPI.java:40) ~[?:?]
at fr.black_eyes.lootchest.LootChestHologram.createHologram(LootChestHologram.java:156) ~[?:?]
at fr.black_eyes.lootchest.LootChestHologram.getHologram(LootChestHologram.java:166) ~[?:?]
at fr.black_eyes.lootchest.LootChestHologram.setText(LootChestHologram.java:126) ~[?:?]
at fr.black_eyes.lootchest.LootChestHologram.setLoc(LootChestHologram.java:79) ~[?:?]
at fr.black_eyes.lootchest.Lootchest.createchest(Lootchest.java:426) ~[?:?]
at fr.black_eyes.lootchest.Lootchest.spawn(Lootchest.java:533) ~[?:?]
at fr.black_eyes.lootchest.Lootchest.spawn(Lootchest.java:451) ~[?:?]
at fr.black_eyes.lootchest.Utils$1.run(Utils.java:170) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[forge:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[forge:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:997) ~[?:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:336) ~[?:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:943) ~[?:?]
at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:775) ~[?:?]
at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:265) ~[?:?]
at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by Guarmanda** [comment]
Fixed chinese characters not supported
First error couldn't be reproduced, nothing explained by the user
